### PR TITLE
Use include_str! instead of runtime read

### PR DESCRIPTION
**Pull request by SekoiaTree**
Changed line 7 to use include_str! instead of a runtime file read. It's vaguely faster

### CODE REVIEW

**Comment by shilangyu** [comment]
Thanks! Could you change it in `day01.rs` as well then?

**Comment by shilangyu** [comment]
Have you tried to compile it?

`include_str!` takes a path relative to the file not the cwd, so it won't compile

**Comment by SekoiaTree** [comment]
Oh right, sorry

**Comment by SekoiaTree** [comment]
Alright, it looks like `cargo eval` runs relative to the installation of eval, because the example of include_str! doesn't work. So uuuh oh well.

**Comment by shilangyu** [comment]
Either way, thanks, I have implemented it: https://github.com/shilangyu/AoC-2020/commit/8aaa5e44096aacb082dfeec0a177fa075a3ca0a4

**Pull request closed without merging**
